# @package _global_
optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4  # Lower learning rate
  weight_decay: 1e-2  # Increased weight decay for regularization
  betas: [0.9, 0.98]  # Beta values recommended for transformers
  eps: 1e-8 