# @package _global_
decoder:
  _target_: emg2qwerty.decoder.CTCBeamDecoder
  beam_size: 100
  max_labels_per_timestep: 5
  lm_path: ${hydra:runtime.cwd}/models/lm/wikitext-103-6gram-charlm.bin
  lm_weight: 3.0
  insertion_bonus: 1.0
  insertion_penalty: 1.0
  blank_bonus: 0.1
  delete_key: Key.backspace
